### ISSUE TITLE
Rule discussion: one-var

### ISSUE THREAD

**Issue by acontreras89** [redradix/javascript-style-guide#1]
I would like to bring up some discussion about [rule `one-var`.](http://eslint.org/docs/rules/one-var)

I personally don't like our current configuration for the rule. I believe a proper use of both single and multiple declarations can improve readability by providing contextual information, like which variables are related to each other. 
I would love to turn this rule `'off'`, but what do you guys think?

**Comment by roman01la** [comment]
I'm fine with both styles, but personally making separate declarations per variable. One argument to use this style is that diffs in Git are easier to read when merging.

**Comment by acontreras89** [comment]
Closing this as the project is not being maintained anymore.
